---
# Installation
nifi_package_mirror: "https://archive.apache.org/dist"
nifi_version: "1.19.0"

nifi_archive_filename: "nifi-{{ nifi_version }}-bin.zip"
nifi_archive_source: "{{ nifi_package_mirror }}/nifi/{{ nifi_version }}/{{ nifi_archive_filename }}"
nifi_archive_hash_sha256: "54be4c13fa81a3fe4860a728288b79fadc1e122904b19f1279a12017412ebd1a"

nifi_os_user_name: "nifi"
nifi_os_group_name: "{{ nifi_os_user_name }}"

# Memory config
nifi_jvm_heap_memory_initial: "512m"
nifi_jvm_heap_memory_max: "2560m"

# Host/Port config
#nifi_freemyip_domain_name: "something.freemyip.com" # Dynamic IP service, leave undefined if not needed
#nifi_freemyip_domain_token: "something-token" # Dynamic IP service, leave undefined if not needed
nifi_domain_name: "input.data-platform.example" # If you use freemyip.com for a domain name, put it here
nifi_listener_port: 8080
nifi_remote_input_port: 10000
nifi_cluster_node_protocol_port: 11000

# HTTPS config: we'll use the same truststore (storage of trusted authority certificates) as keystore (client key certificates) because we don't use them for authorization
#nifi_security_truststore_file_name: "truststore.p12"
#nifi_security_truststore_passwd: "Password_123"

# OAuth config
# https://console.developers.google.com/ -> New Project -> APIs and Services -> Credentials
# Web application, Authorized redirect URIs: https://{{ nifi_domain_name }}:{{ nifi_listener_port }}/nifi-api/access/oidc/callback
#nifi_oauth_admin_name: "username@gmail.com"
#nifi_oauth_client_id: "1234567890.apps.googleusercontent.com"
#nifi_oauth_client_secret: "OAuthSecret_123"

# API open ports
#firewall_open_ports: # If you need to expose an external API, leave undefined if not needed
#  - '1337'
